### ISSUE TITLE
Update README with newest Docker container information

### ISSUE THREAD

**Issue by fbartusch** [pereiramemo/BiG-MEx#13]
Hello,

we try to deploy BiG-MEx on our HPC-Cluster via Singularity, but the Docker images mentioned in the README and wiki aren't partially not available. It's also not very clear in the documentation which container is actually relevant or not, as the container names in the wrapper scripts and the README aren't always the same.

Not available (or not public?) images mentioned in README/Wiki
- epereira/bgc_dom_div

Not available (or not public?) images mentioned in the corresponding scripts
- [epereira/bgc_dom_amp_div](https://github.com/pereiramemo/BiG-MEx/blob/master/run_bgc_dom_div.bash#L48)
- [epereira/bgc_dom_meta_div](https://github.com/pereiramemo/BiG-MEx/blob/master/run_bgc_dom_div.bash#L106)

Can you update the README with the newest information needed to deploy BiG-MEx?

Thanks in advance and best regards,
Felix

**Comment by pereiramemo** [comment]
Hi Felix, 

Thanks for your message. 
We are in the middle of an update right now: we are adding a module to analyze amplicon data.  Please try to download BiG-MEx in a week from now. We should have everything working properly by then.

Best, 

Emiliano

**Comment by fbartusch** [comment]
Hi Emiliano,

thanks for your fast reply. I will try in a week from now again and happy to test the update.

Cheers,
Felix
