### ISSUE TITLE
Wiki: OSD*_orfs.faa missing in metagenomic_samples.tar.gz

### ISSUE THREAD

**Issue by fbartusch** [pereiramemo/BiG-MEx#14]
Hello,

I try to go through the [Getting Started](https://github.com/pereiramemo/BiG-MEx/wiki/Getting-started#getting-started) in your Wiki, but it seems that there are files missing in the metagenomic_samples.tar.gz.

The Wiki says:

> However, for this tutorial, we included the predicted ORFs (i.e., OSD*_orfs.faa) in metagenomic_samples.tar.gz.

But there are no OSD*_orfs.faa files in the archive download from: `https://owncloud.mpi-bremen.de/index.php/s/fibkaNcmGifhLv9/download`.

Best Regards,
Felix

**Comment by pereiramemo** [comment]
Hi Felix, 

I am happy to see you are using BiG-MEx.
Yes, you are right. I have to update the link. I can do it tonight.

Otherwise, you can generate your own *.faa files with fraggenescan or fraggenescanplusplus.

https://sourceforge.net/projects/fraggenescan/
https://github.com/unipept/FragGeneScanPlusPlus

Best, 

Emiliano

**Comment by fbartusch** [comment]
Dear Emiliano,

can you update the URL in the wiki? The curl just downloads an error message now.

> I am happy to see you are using BiG-MEx.

It's not me, but a user on our cluster. I converted the containers to Singularity and patched the scripts and want to test if everything is fine.

Best Regards,
Felix

**Comment by pereiramemo** [comment]
Hi Felix,

I am on it. I'll let you know as soon as I have the new data uploaded.
Please note that (for the sake of testing it) you could also annotate the
BGC domains in the DNA sequences.
For example:

"${BIN}/run_bgc_dom_annot.bash" \
  "${OUTPUT_DIR}/OSD2_ME_n_SE_shotgun_workable_merged.fastq.gz" \
  "${OUTPUT_DIR}/out_dom_annot_osd2" \
  --intype dna \
  --nslots 4 \
  --sample "osd2" \
  --verbose t

Best,

Emiliano

**Comment by pereiramemo** [comment]
Dear Felix, 

The data is uploaded (and the link updated).
It should work now. Please let me know otherwise. 

Best, 

Emiliano

**Comment by fbartusch** [comment]
Dear Emiliano,

the whole tutorial works now for me, thank you very much.
I had a small issue with a script in one container. I think I'll open a ticket for it later, but then everything should work on our cluster.

If you want I can make a pull request with the wrapper scripts for Singularity containers later this day.

Cheers,
Felix
