### ISSUE TITLE
Question Pertaining to FragGeneScanPlus

### ISSUE THREAD

**Issue by raufs** [pereiramemo/BiG-MEx#16]
Hi,

I recently read your Biorxiv manuscript on BiG-MEx and really liked the methods you developed and found the subsequent analyses super interesting as well!  

I am attempting to follow the workflows detailed in the wiki and perform ORF calling on my metagenome samples; however, I am unsure which FragGeneScan code base to use. 

The official FragGeneScanPlus appears to have an unresolved issue related to translating of reverse frames, as is well described in the following ticket: https://github.com/hallamlab/FragGeneScanPlus/issues/19 . A more up to date fork of this repo, called FragGeneScanPlusPlus [https://github.com/unipept/FragGeneScanPlusPlus], maintained by a different group, appears to resolve this issue and matches the output of the original FragGeneScan (by Rho et al 2010) for a test case (the one from the fore mentioned git issue ticket*).

Can you please confirm if FragGeneScanPlusPlus [https://github.com/unipept/FragGeneScanPlusPlus] is the program you recommend to users for metagenomic ORF calling?

Kind regards,
Rauf

**Comment by genomewalker** [comment]
Hi @raufs 

the correct version is the one from Unipept. The original one provide incorrect gene predictions. We will update the wiki with this information.

Thank you for using BiG-MEx

Antonio

**Comment by raufs** [comment]
Great, thank you for the quick response!
